//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::channel_users::Entity as ChannelUsers;
pub use super::channels::Entity as Channels;
pub use super::channels_errors::Entity as ChannelsErrors;
pub use super::items::Entity as Items;
pub use super::users::Entity as Users;
pub use super::users_items::Entity as UsersItems;
