name: Build and deploy

on: [workflow_dispatch]

jobs:
  docker:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud/pedr0
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push migrations
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./migrations/
          platforms: linux/amd64,linux/arm64
          tags: rg.nl-ams.scw.cloud/pedr0/rss-aggregator-migrations:latest
      -
        name: Build and push API
        uses: docker/build-push-action@v3
        with:
          push: true
          target: api
          platforms: linux/amd64,linux/arm64
          tags: rg.nl-ams.scw.cloud/pedr0/rss-aggregator-api:latest
      -
        name: Build and push fetcher
        uses: docker/build-push-action@v4
        with:
          push: true
          target: fetcher
          platforms: linux/amd64,linux/arm64
          tags: rg.nl-ams.scw.cloud/pedr0/rss-aggregator-fetcher:latest
