name: Build and deploy

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud/pedr0
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push API
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rg.nl-ams.scw.cloud/pedr0/rss-aggregator:latest
      -
        name: Build and push fetcher
        uses: docker/build-push-action@v3
        with:
          file: fetcher.Dockerfile
          push: true
          tags: rg.nl-ams.scw.cloud/pedr0/rss-aggregator-fetcher:latest          
