name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  amd64:
    name: Build Linux AMD64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        env:
          SQLX_OFFLINE: true
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: amd64
          path: |
            target/x86_64-unknown-linux-gnu/release/rss-aggregator
            target/x86_64-unknown-linux-gnu/release/fetcher
  arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        env:
          SQLX_OFFLINE: true
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: arm64
          path: |
            target/aarch64-unknown-linux-gnu/release/rss-aggregator
            target/aarch64-unknown-linux-gnu/release/fetcher
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [amd64, arm64]
    steps:
      - uses: actions/download-artifact@v3
      - name: Rename files
        run: |
          mv amd64/fetcher fetcher-amd64
          mv amd64/rss-aggregator rss-aggregator-amd64
          mv arm64/fetcher fetcher-arm64
          mv arm64/rss-aggregator rss-aggregator-arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            fetcher-amd64
            rss-aggregator-amd64
            fetcher-arm64
            rss-aggregator-arm64
  docker:
    name: Build docker images
    runs-on: ubuntu-latest
    needs: [ amd64, arm64 ]
    env:
      docker_tag: "${github.ref//./-}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud/pedr0
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: api
          platforms: linux/amd64,linux/arm64
          tags: |
            rg.nl-ams.scw.cloud/pedr0/rss-aggregator-api:latest
            rg.nl-ams.scw.cloud/pedr0/rss-aggregator-api:${docker_tag}
      - name: Build and push fetcher docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: fetcher
          platforms: linux/amd64,linux/arm64
          tags: |
            rg.nl-ams.scw.cloud/pedr0/rss-aggregator-fetcher:latest
            rg.nl-ams.scw.cloud/pedr0/rss-aggregator-fetcher:${docker_tag}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/download-artifact@v3
      - name: Rename files
        run: |
          mv amd64/fetcher fetcher-amd64
          mv amd64/rss-aggregator rss-aggregator-amd64
          mv arm64/fetcher fetcher-arm64
          mv arm64/rss-aggregator rss-aggregator-arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            fetcher-amd64
            rss-aggregator-amd64
            fetcher-arm64
            rss-aggregator-arm64
