name: Build and deploy

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com/rss-repository
          username: ${{ secrets.DI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DI_DOCKERHUB_TOKEN }}
      -
        name: Build and push API
        uses: docker/build-push-action@v3
        with:
          push: true
          target: api
          tags: registry.digitalocean.com/rss-repository/rss-aggregator-api:latest
      -
        name: Build and push fetcher
        uses: docker/build-push-action@v3
        with:
          push: true
          target: fetcher
          tags: registry.digitalocean.com/rss-repository/rss-aggregator-fetcher:latest
          