name: Build and deploy

on: [pull_request]

jobs:
  amd64:
    name: Linux AMD64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        env:
          SQLX_OFFLINE: true
        with:
          command: build
          args: --release
  arm64:
    name: Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        env:
          SQLX_OFFLINE: true
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu