name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  set-vars:
    name: Build docker tag
    runs-on: ubuntu-latest
    outputs:
      version_dashed: ${{ steps.vars.outputs.version_dashed }}
    steps:
      - name: set values
        id: vars
        run: |
          echo "version_dashed=${GITHUB_REF#refs/tags/}" | tr . - >> $GITHUB_OUTPUT
  build:
    strategy:
      matrix:
        include:
          - arch: "x86_64-unknown-linux-gnu"
            docker-arch: "amd64"
          - arch: "aarch64-unknown-linux-gnu"
            docker-arch: "arm64"
          - arch: "armv7-unknown-linux-gnueabihf"
            docker-arch: "arm"
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libssl
        run: sudo apt-get install -y pkg-config libssl-dev
      - name: Update toolchain to last stable and install croos
        run: rustup update stable && rustup default stable && cargo install cross
      - name: Compile
        run: cross build --release --target ${{ matrix.arch }}
        env:
          SQLX_OFFLINE: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.docker-arch }}
          path: |
            target/${{ matrix.arch }}/release/harss-api
  docker:
    name: Build docker images
    runs-on: ubuntu-latest
    needs: [ build, set-vars ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: rg.nl-ams.scw.cloud/pedr0
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            rg.nl-ams.scw.cloud/pedr0/harss-api:latest
            rg.nl-ams.scw.cloud/pedr0/harss-api:${{ needs.set-vars.outputs.version_dashed }}
            rg.nl-ams.scw.cloud/pedr0/harss-api:${{ env.GITHUB_REF_NAME }}_${{ env.GITHUB_RUN_ID }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/download-artifact@v4
      - name: Rename files
        run: |
          for i in $(ls -d */ | sed 's#/##')
          do
            mv $i/harss-api harss-api-$i
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            harss-api-*
