name: Check, test, lint

on: [pull_request, push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo check --verbose
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: harss
          POSTGRES_DB: harss
          POSTGRES_USER: harss
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      SQLX_OFFLINE: true
      DATABASE_URL: "postgres://harss:harss@localhost/harss"
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --all --verbose 
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warning
  spectral:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'static/openapi.yaml'
